server.port=8081

spring.datasource.url=jdbc:postgresql://db-aules.uji.es:5432/ei102725vcp
spring.datasource.username=ei102725vcp
spring.datasource.password=ei102725vcp
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.leak-detection-threshold=60000

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

server.servlet.session.timeout=6h

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pauhenhao@gmail.com
spring.mail.password=jvzy lmcs kujk ofwz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


